spring:
  application:
    name: user
  datasource:
    url: jdbc:mariadb://localhost:3306/loja_online
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      user: ${KAFKA_TOPIC:user}
    consumer:
      group-id: user-group
      auto-offset-reset: latest
    server:
      port: 9092
logging:
  level:
    org:
      apache:
        kafka: OFF

api:
  security:
    token:
      secret: "${JWT_SECRET:32rASD213dsa}"

server:
    port: 8072

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        instanceId: ${spring.application.name}:${spring.application.instanceId:${random.value}}
debug: true