spring:
  application:
    name: user
  datasource:
    url: jdbc:mariadb://localhost:3306/loja_online
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  zookeeper:
    client-port: zookeeper:2181

  kafka:
    kafka-zookeeper:
      connect: zookeeper:2181
    admin:
      topics:
        topic:
          name: UserTopic
          partition: 1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: kafka:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: User-group
      enable-auto-commit: false
      bootstrap-servers: kafka:9092
    bootstrap-servers: kafka:9092
    properties:
      security:
        protocol: PLAINTEXT
  level:
    org:
      apache:
        kafka: debug

  api:
    security:
      token:
        secret: "${JWT_SECRET:32rASD213dsa}"

  server:
      port: 8072

  debug: true


