version: '4.30.0'
services:
  api:
    build:
      depends_on:
        - db
      ports:
        - 8080:8080
      env_file:
        - .env
    db:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: loja_online
        MYSQL_USER: root
        MYSQL_PASSWORD: 1234
        ports:
          - 3306:3306
        command: --default-authentication-plugin=mysql_native_password