spring:
  application:
    name: eureka-server
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      eureka: ${KAFKA_TOPIC:eureka}
    consumer:
      group-id: eureka-group
      auto-offset-reset: latest
    server:
      port: 9092
server:
    port: 8761

eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
logging:
  level:
    org:
      apache:
        kafka: OFF