spring:
  application:
    name: item
  datasource:
    url: jdbc:mariadb://localhost:3306/loja_online
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      item: ${KAFKA_TOPIC:item}
    consumer:
      group-id: item-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

logging:
  level:
    org:
      apache:
        kafka: OFF

server:
  port: 8081

api:
  security:
    token:
      secret: "${JWT_SECRET:32rASD213dsa}"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instanceId:${random.value}}