spring:
  application:
    name: Cart


server:
  port: 0

eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
    instance:
        instanceId: ${spring.application.name}:${spring.application.instanceId:${random.value}}
