CREATE TABLE ITENS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    QUANTITY INT NOT NULL,
    DATATIME DATETIME NOT NULL,
    CATEGORY ENUM
);